Create HW2.md
aliamoiseeva/DevOps-Epam-course pull request #3
Opened 2021-12-05 17:30 UTC by aliamoiseeva

2021-12-05 23:58 UTC, aliamoiseeva commented
@tsukabris

2021-12-13 18:40 UTC, Tsukabris commented on HW2.md
> +3**. Скрипт принимает любое количество записей в первом файле и обрабатывает их последовательно.
В первом файле у тебя изначально (задание 3) содержится одна строка с указанием одного пути до директории. В случае с заданием 3** в этом же файле может содержаться любое количество строк, и для каждой из них должны выполняться идентичные операции.

2021-12-13 18:51 UTC, Tsukabris requested changes
Сделано и оформлено хорошо
Всё, кроме 3** принято

2021-12-13 19:50 UTC, aliamoiseeva commented on HW2.md
> +3**. Скрипт принимает любое количество записей в первом файле и обрабатывает их последовательно.
Поправила, и проверила работу скрипта, выполняет для каждой строки вывод содержимого директорий

2022-02-01 15:51 UTC, merged